### ISSUE TITLE
Feat: 커뮤니티 기능

### ISSUE THREAD

**Issue by kmg0485** [A7-TC2-TeamCode200/MRLA#4]
- [x] 커뮤니티 글 모델 작성
- [x] 커뮤니티 댓글 모델 작성
- [x] 커뮤니티 url 설정
- [x] 커뮤니티 데이터 설정

**Comment by ja2w0nii** [comment]
- [x] 커뮤니티 게시글 좋아요 등록/취소 기능 추가

**Comment by R5Z** [comment]
- [ ] 커뮤니티 게시글 모델에 태그 필드 추가 필요
